### ISSUE TITLE
Изменить содержимое таблицы admin/orders

### ISSUE THREAD

**Issue by Korako2** [Korako2/ISDB#145]
Сейчас она имеет такие колонки:
![image](https://github.com/Korako2/ISDB/assets/93494061/44c54b89-a919-46ad-8127-a8c509e07e58)

Заменить:
Имя заказчика -> ID Заказчика
Имя водителя -> ID Водителя
Это нужно для того, чтобы мы могли опознать кто и куда везет заказ.

Кроме этого реализовать аналогично таблице в index: вместо ID пунктов получения и отправления сделать строки состоящие из:
1) Город
2) Улица
3) Дом
4) Корпус

**Comment by Moleus** [comment]
если когда-нибудь мб
